// Local icon assets
export const serviceIconAssets: Record<string, string> = {
  // Navigation
  ChevronLeft: '/assets/icons/figma/ServiceIcon/ChevronLeft.svg',
  ChevronRight: '/assets/icons/figma/ServiceIcon/ChevronRight.svg',
  ChevronUp: '/assets/icons/figma/ServiceIcon/ChevronUp.svg',
  ChevronDown: '/assets/icons/figma/ServiceIcon/ChevronDown.svg',

  // User & Account
  User: '/assets/icons/figma/ServiceIcon/User.svg',
  Logout: '/assets/icons/figma/ServiceIcon/Logout.svg',
  Backpack: '/assets/icons/figma/ServiceIcon/Backpack.svg',

  // Actions
  Check: '/assets/icons/figma/ServiceIcon/Check.svg',
  Plus: '/assets/icons/figma/ServiceIcon/Plus.svg',
  Close: '/assets/icons/figma/ServiceIcon/Close.svg',
  Search: '/assets/icons/figma/ServiceIcon/Search.svg',
  Filter: '/assets/icons/figma/ServiceIcon/Filter.svg',
  Download: '/assets/icons/figma/ServiceIcon/Download.svg',
  ExternalLink: '/assets/icons/figma/ServiceIcon/ExternalLink.svg',
  Pen: '/assets/icons/figma/ServiceIcon/Pen.svg',

  // Favorites & Rating
  HeartOn: '/assets/icons/figma/ServiceIcon/HeartOn.svg',
  HeartOff: '/assets/icons/figma/ServiceIcon/HeartOff.svg',
  Star: '/assets/icons/figma/ServiceIcon/Star.svg',
  StarEmpty: '/assets/icons/figma/ServiceIcon/StarEmpty.svg',

  // Communication
  Phone: '/assets/icons/figma/ServiceIcon/Phone.svg',
  Whatsapp: '/assets/icons/figma/ServiceIcon/Whatsapp.svg',

  // Social Media
  Facebook: '/assets/icons/figma/ServiceIcon/Facebook.svg',
  Instagram: '/assets/icons/figma/ServiceIcon/Instagram.svg',
  Youtube: '/assets/icons/figma/ServiceIcon/Youtube.svg',
  Google: '/assets/icons/figma/ServiceIcon/Google.svg',

  // Location & Travel
  Map: '/assets/icons/figma/ServiceIcon/Map.svg',
  Bed: '/assets/icons/figma/ServiceIcon/Bed.svg',
  Calendar: '/assets/icons/figma/ServiceIcon/Calendar.svg',
  Flight: '/assets/icons/figma/ServiceIcon/Flight.svg',
  Clock: '/assets/icons/figma/ServiceIcon/Clock.svg',
  Bus: '/assets/icons/figma/ServiceIcon/Bus.svg',

  // UI Elements
  Menu: '/assets/icons/figma/ServiceIcon/Menu.svg',
  Info: '/assets/icons/figma/ServiceIcon/Info.svg',
  Circle: '/assets/icons/figma/ServiceIcon/Circle.svg',
  CircleCheck: '/assets/icons/figma/ServiceIcon/CircleCheck.svg',
  CheckTrue: '/assets/icons/figma/ServiceIcon/CheckTrue.svg',
  CheckFalse: '/assets/icons/figma/ServiceIcon/CheckFalse.svg',
  EyeOpen: '/assets/icons/figma/ServiceIcon/EyeOpen.svg',
  EyeClosed: '/assets/icons/figma/ServiceIcon/EyeClosed.svg',

  // Services & Features
  Breakfast: '/assets/icons/figma/ServiceIcon/Breakfast.svg',
  Shield: '/assets/icons/figma/ServiceIcon/Shield.svg',
  Assistance: '/assets/icons/figma/ServiceIcon/Assistance.svg',
  Guide: '/assets/icons/figma/ServiceIcon/Guide.svg',
  App: '/assets/icons/figma/ServiceIcon/App.svg',
  GpsTrack: '/assets/icons/figma/ServiceIcon/GpsTrack.svg',
  Tree: '/assets/icons/figma/ServiceIcon/Tree.svg',
  Gift: '/assets/icons/figma/ServiceIcon/Gift.svg',
  Spinner: '/assets/icons/figma/ServiceIcon/Spinner.svg',
  Pdf: '/assets/icons/figma/ServiceIcon/Pdf.svg',
  Stopwatch: '/assets/icons/figma/ServiceIcon/Stopwatch.svg',
  Invoice: '/assets/icons/figma/ServiceIcon/Invoice.svg',
  Contract: '/assets/icons/figma/ServiceIcon/Contract.svg',
  Estimate: '/assets/icons/figma/ServiceIcon/Estimate.svg',
  Sign: '/assets/icons/figma/ServiceIcon/Sign.svg',
  Shop: '/assets/icons/figma/ServiceIcon/Shop.svg',
  QRCode: '/assets/icons/figma/ServiceIcon/QRCode.svg',
  Kilometers: '/assets/icons/figma/ServiceIcon/GpsTrack.svg',
  Union: '/assets/icons/figma/ServiceIcon/Union.svg',
  // New icons
  Payment: '/assets/icons/figma/ServiceIcon/ServiceIconNew/Payment.svg',
  Cancellation: '/assets/icons/figma/ServiceIcon/ServiceIconNew/Cancellation.svg',
  Switch: '/assets/icons/figma/ServiceIcon/ServiceIconNew/Switch.svg',
  Password: '/assets/icons/figma/ServiceIcon/ServiceIconNew/Password.svg',
  PlanSolid: '/assets/icons/figma/ServiceIcon/ServiceIconNew/PlanSolid.svg',
};

// Icon dimensions from Figma
export const iconDimensions: Record<string, { width: number; height: number }> = {
  User: { width: 11.375, height: 13 },
  ChevronLeft: { width: 5.881, height: 10.95 },
  ChevronRight: { width: 5.881, height: 10.925 },
  ChevronUp: { width: 10.95, height: 5.907 },
  ChevronDown: { width: 10.975, height: 5.881 },
  HeartOn: { width: 13.016, height: 11.387 },
  HeartOff: { width: 13.016, height: 11.387 },
  Backpack: { width: 11.375, height: 13 },
  Star: { width: 13.613, height: 13.005 },
  StarEmpty: { width: 13.613, height: 13.005 },
  Search: { width: 12.994, height: 13.019 },
  Phone: { width: 10.986, height: 10.986 },
  Calendar: { width: 9.625, height: 11 },
  Check: { width: 9.636, height: 6.886 },
  Plus: { width: 8.938, height: 8.938 },
  Logout: { width: 12.987, height: 11.375 },
  Close: { width: 8.138, height: 8.138 },
  Map: { width: 8.25, height: 10.984 },
  Bed: { width: 13.75, height: 9.625 },
  Menu: { width: 11.375, height: 9.344 },
  ExternalLink: { width: 8.138, height: 8.125 },
  Filter: { width: 11.375, height: 9.344 },
  Download: { width: 9.75, height: 11.375 },
  EyeOpen: { width: 13.488, height: 10.5 },
  EyeClosed: { width: 15.004, height: 12.002 },
  Whatsapp: { width: 11.375, height: 11.375 },
  Instagram: { width: 11, height: 11 },
  Facebook: { width: 12.59375, height: 12.517578125 },
  Youtube: { width: 13.888671875, height: 9.75 },
  Google: { width: 13.458, height: 13.458 },
  Pen: { width: 12.991, height: 12.977 },
  Circle: { width: 13, height: 13 },
  CircleCheck: { width: 13, height: 13 },
  CheckTrue: { width: 11.375, height: 11.375 },
  CheckFalse: { width: 11.375, height: 11.349609375 },
  Info: { width: 13, height: 13 },
  QRCode: { width: 11.375, height: 11.375 },
  Flight: { width: 14.644, height: 13 },
  Clock: { width: 13, height: 13 },
  Bus: { width: 13, height: 13 },
  Breakfast: { width: 13, height: 13.025 },
  Shield: { width: 12.189, height: 12.949 },
  Assistance: { width: 13, height: 13 },
  Guide: { width: 10.5, height: 12 },
  App: { width: 8.25, height: 12 },
  GpsTrack: { width: 12, height: 12 },
  Tree: { width: 10.5, height: 12 },
  Gift: { width: 12, height: 12 },
  Spinner: { width: 13, height: 13 },
  Pdf: { width: 12.594, height: 13 },
  Stopwatch: { width: 10.563, height: 13 },
  Invoice: { width: 9.75, height: 12.995 },
  Contract: { width: 9.75, height: 13 },
  Estimate: { width: 14.625, height: 9.75 },
  Sign: { width: 16.25, height: 11.375 },
  Shop: { width: 10.5, height: 12 },
  Kilometers: { width: 17, height: 17 },
  Union: { width: 12, height: 13 },
  Payment: { width: 14.625, height: 11.375 },
  Cancellation: { width: 13, height: 13 },
  Switch: { width: 12.213, height: 11.375 },
  Password: { width: 12.188, height: 13 },
  PlanSolid: { width: 14.625, height: 13 },
  Google: { width: 13.458, height: 13.458 },
};
